influx:
  image: tutum/influxdb
  container_name: influx
  ports:
    - 8086:8086
    - 8083:8083
serializer:
  build: ../serializer/
  container_name: serializer
frontend:
  build: ../frontend/
  container_name: frontend
broker:
  build: ../broker/
  container_name: broker
sensor:
  build: ../sensor/
  container_name: sensor 
actuator:
  build: ../actuator/
  container_name: actuator
