version: '2'
services:
  influx:
    image: tutum/influxdb
    container_name: influx
    volumes:
      - "./data:/data"
    ports:
      - "8083:8083"
    expose:
      - "8086"
  serializer:
    env_file: ./dev.conf
    build: ../serializer/
    container_name: serializer
    links:
      - influx:influx
    depends_on:
      - influx
  broker:
    env_file: ./dev.conf
    build: ../broker/
    container_name: broker
    links:
      - serializer:serializer
    depends_on:
      - serializer
  sensor:
    env_file: ./dev.conf
    build: ../sensor/
    container_name: sensor
    links:
      - broker:broker
    depends_on:
      - broker
  actuator:
    env_file: ./dev.conf
    build: ../actuator/
    container_name: actuator
    links:
      - broker:broker
    depends_on:
      - broker
  frontend:
    env_file: ./dev.conf
    build: ../frontend/
    links:
      - serializer:serializer
      - actuator:actuator
    container_name: frontend
    ports:
      - "10001:10001"
    depends_on:
      - serializer
      - actuator
