influx:
  image: tutum/influxdb
  container_name: influx
  ports:
    - 8086:8086
    - 8083:8083
serializer:
  build: ../services/serializer/
  container_name: serializer
  environment:
    - INFLUX_HOST=influx
    - SERIALIZER_PORT=10000
  links:
    - influx:influx
  ports:
    - 10000:10000
frontend:
  build: ../frontend/
  container_name: frontend
  environment:
    - SERIALIZER_HOST=serializer
    - SERIALIZER_PORT=10000
    - FRONTEND_PORT=10001
  links:
    - serializer:serializer
  ports:
    - 10001:10001
broker:
  build: ../services/broker/
  container_name: broker
  environment:
    - SERIALIZER_HOST=serializer
    - SERIALIZER_PORT=10000
  links:
    - serializer:serializer
  ports:
    - 10002:10002
    - 1883:1883
    - 8883:8883
sensor:
  build: ../services/sensor/
  container_name: sensor
  environment:
    - BROKER_HOST=broker
  links:
    - broker:broker
  ports:
    - 10003:10003
